before_script:
  - sh scripts/init_ci.sh
  - sh scripts/dependencies.sh
  - sh scripts/init_test.sh

test:
  script:
    - python run_tests.py -ci

services:
  - postgres:latest

variables:
  POSTGRES_DB: triviapatente_test
  POSTGRES_USER: ted
  POSTGRES_PASSWORD: ted
