# -*- coding: utf-8 -*-
shared_map = {
    "Patenti di guida, sistema sanzionatorio, documenti di circolazione, obblighi verso agenti, uso di lenti e altri apparecchi": {"color": "#F44336", "hint": "Patenti e documenti", "id": 1},
    "Segnali di pericolo": {"color": "#9C27B0", "hint": "Segnali di pericolo", "id": 2},
    "Responsabilità civile, penale e amministrativa, assicurazione r.c.a. e altre forme assicurative legate al veicolo": {"color": "#E040FB", "hint": "Responsabilità in strada", "id": 3},
    "Uso delle luci e dei dispositivi acustici, spie e simboli": {"color": "#9575CD", "hint": "Luci, dispositivi e spie", "id": 4},
    "Distanza di sicurezza": {"color": "#3F51B5", "hint": "Distanza di sicurezza", "id": 5},
    "Norme sul sorpasso": {"color": "#1A237E", "hint": "Sorpasso", "id": 6},
    "Incidenti stradali e comportamenti in caso di incidente": {"color": "#00BCD4", "hint": "Incidenti", "id": 7},
    "Pannelli integrativi dei segnali": {"color": "#4CAF50", "hint": "Pannelli integrativi", "id": 8},
    "Segnaletica orizzontale e segni sugli ostacoli": {"color": "#2E7D32", "hint": "Segnali orizzontali", "id": 9},
    "Esempi di precedenza (ordine di precedenza agli incroci)": {"color": "#00E676", "hint": "Precedenza", "id": 10},
    "Segnali complementari, segnali temporanei e di cantiere": {"color": "#CDDC39", "hint": "Altri segnali", "id": 11},
    "Dispositivi di equipaggiamento, funzione ed uso: cinture di sicurezza, sistemi di ritenuta per bambini, casco protettivo e abbigliamento di sicurezza": {"color": "#C6FF00", "hint": "Sicurezza nel veicolo", "id": 12},
    "Definizioni generali e doveri nell'uso della strada": {"color": "#FFC107", "hint": "Strade", "id": 13},
    "Guida in relazione alle qualità e condizioni fisiche e psichiche, alcool, droga, farmaci e primo soccorso": {"color": "#FF6F00", "hint": "Condizioni psicofisiche", "id": 14},
    "Fermata, sosta, arresto e partenza": {"color": "#A1887F", "hint": "Fermata, sosta, arresto", "id": 15},
    "Segnali di precedenza": {"color": "#607D8B", "hint": "Segnali di precedenza", "id": 16},
    "Segnali di indicazione": {"color": "#039BE5", "hint": "Segnali di indicazione", "id": 17},
    "Norme sulla circolazione dei veicoli": {"color": "#651FFF", "hint": "Circolazione veicoli", "id": 18},
    "Elementi costitutivi del veicolo, manutenzione ed uso, stabilità e tenuta di strada, comportamenti e cautele di guida": {"color": "#D50000", "hint": "Salvaguardia veicolo", "id": 19},
    "Segnali di divieto": {"color": "#3949AB", "hint": "Segnali di divieto", "id": 20},
    "Limiti di velocità, pericolo e intralcio alla circolazione": {"color": "#00ACC1", "hint": "Pericolo e limiti", "id": 21},
    "Segnali di obbligo": {"color": "#006064", "hint": "Segnali di obbligo", "id": 22},
    "Norme varie (ingombro della carreggiata, circolazione su autostrade e strade extraurbane principali, trasporto di persone, pannelli sui veicoli, etc.)": {"color": "#00E5FF", "hint": "Norme varie", "id": 23},
    "Segnalazioni semaforiche e degli agenti del traffico": {"color": "#C0CA33", "hint": "Semafori e agenti", "id": 24},
    "Limitazione dei consumi, rispetto dell'ambiente e inquinamento": {"color": "#827717", "hint": "Inquinamento", "id": 25}
}
