pip install python-engineio
pip install scrypt
pip install greenlet
pip install gevent
pip install gevent-websocket
pip install flask-sqlalchemy
pip install Enum34
pip install pytz
pip install itsdangerous
pip install passlib
pip install flask-httpauth
pip install flask-socketio
pip install validate_email
pip install facebook-sdk
pip install flask-mail
pip install pyfcm
