pip install eventlet
pip install scrypt
pip install flask-sqlalchemy==2.3.2
pip install redis
pip install Enum34
pip install pytz
pip install itsdangerous
pip install passlib
pip install flask-httpauth
pip install Flask-Session
pip install Flask-Limiter
pip install flask-socketio==3.0.0
pip install validate_email
pip install facebook-sdk
pip install flask-mail
pip install pyfcm
pip install premailer
pip install lxml==3.4.4
pip install Flask-APScheduler
pip install requests[security]
